CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    user_role VARCHAR(50) NOT NULL,
    balance NUMERIC(19, 2) NOT NULL DEFAULT 0
);

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    province VARCHAR(255),
    type VARCHAR(100)
);

CREATE TABLE auction_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    base_price NUMERIC(19, 2) NOT NULL,
    step_price NUMERIC(19, 2) NOT NULL,
    deposit_amount NUMERIC(19, 2) NOT NULL,
    current_highest_price NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    settled BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_auction_session_item
        FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT chk_auction_session_prices
        CHECK (base_price >= 0 AND step_price > 0 AND deposit_amount > 0 AND current_highest_price >= base_price),
    CONSTRAINT chk_auction_session_time
        CHECK (end_time > start_time)
);

CREATE INDEX idx_auction_sessions_status_time
    ON auction_sessions (status, start_time, end_time);

CREATE TABLE auction_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    deposit_amount NUMERIC(19, 2) NOT NULL,
    is_refunded BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_auction_registration_user_session UNIQUE (user_id, session_id),
    CONSTRAINT fk_auction_registration_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_auction_registration_session
        FOREIGN KEY (session_id) REFERENCES auction_sessions (id),
    CONSTRAINT chk_auction_registration_deposit CHECK (deposit_amount > 0)
);

CREATE INDEX idx_auction_registrations_session
    ON auction_registrations (session_id);

CREATE TABLE bid_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    bid_amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_bid_history_session
        FOREIGN KEY (session_id) REFERENCES auction_sessions (id),
    CONSTRAINT fk_bid_history_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_bid_history_amount CHECK (bid_amount > 0)
);

CREATE INDEX idx_bid_histories_session_created_at
    ON bid_histories (session_id, created_at);
